// src/lib/__mocks__/listings.ts

import { User, UserRole, Listing, ListingCardData } from "@/types";
import { v4 as uuidv4 } from "uuid";

// ---------------------------------------------------------------------------
// Utilisateurs factices
// ---------------------------------------------------------------------------
export const MOCK_USERS: User[] = [
  {
    id: uuidv4(),
    name: "Alice Dupont",
    avatar_url: "https://picsum.photos/seed/alice/200/200",
    role: "member" as UserRole,
    created_at: new Date().toISOString(),
    email: "alice@example.com",
  },
  {
    id: uuidv4(),
    name: "Blaise Ngoma",
    avatar_url: "https://picsum.photos/seed/blaise/200/200",
    role: "certified" as UserRole,
    created_at: new Date().toISOString(),
    email: "blaise@example.com",
  },
  {
    id: uuidv4(),
    name: "Célestine Mavoungou",
    avatar_url: "https://picsum.photos/seed/celestine/200/200",
    role: "vip" as UserRole,
    created_at: new Date().toISOString(),
    email: "celestine@example.com",
  },
];

// ---------------------------------------------------------------------------
// Annonces factices liées aux utilisateurs
// ---------------------------------------------------------------------------
export const MOCK_LISTINGS: Listing[] = [
  {
    id: uuidv4(),
    slug: "mireille-23",
    title: "Mireille, 23 ans",
    highlight: "Massage sensuel & relaxation",
    description: "Massage sensuel & relaxation, dans un cadre raffiné et discret à Bacongo.",
    category: "categorie-b" as const,
    option_type: "option_2" as const,
    mobility: "les_deux" as const,
    city: "brazzaville" as const,
    district: "bacongo",
    price_xaf: 25_000,
    price_unit: "service",
    rates: [],
    cover_url: "https://picsum.photos/seed/mireille-23/800/600",
    images: [],
    video_url: null,
    video_poster_url: null,
    rating: 4.8,
    reviews_count: 12,
    is_vip: true,
    is_verified: true,
    is_available_now: true,
    boosted_until: new Date(Date.now() + 86400000).toISOString(),
    whatsapp_phone: "+242069123456",
    amenities: ["Wifi", "Climatisation"],
    languages: ["fr"],
    availability: [],
    created_at: new Date().toISOString(),
    user_id: MOCK_USERS[2].id,
  },
  {
    id: uuidv4(),
    slug: "sonia-25",
    title: "Sonia, 25 ans",
    highlight: "Accompagnement VIP & Soirées",
    description: "Accompagnement d'exception pour vos soirées et événements à Pointe-Noire.",
    category: "categorie-c" as const,
    option_type: "option_1" as const,
    mobility: "a_domicile" as const,
    city: "pointe-noire" as const,
    district: "centre",
    price_xaf: 25_000,
    price_unit: "service",
    rates: [],
    cover_url: "https://picsum.photos/seed/sonia-25/800/600",
    images: [],
    video_url: null,
    video_poster_url: null,
    rating: 4.5,
    reviews_count: 8,
    is_vip: false,
    is_verified: true,
    is_available_now: true,
    whatsapp_phone: "+242055678901",
    amenities: ["Huiles essentielles"],
    languages: ["fr", "en"],
    availability: [],
    created_at: new Date().toISOString(),
    user_id: MOCK_USERS[1].id,
  },
  {
    id: uuidv4(),
    slug: "grace-22",
    title: "Grace, 22 ans",
    highlight: "Rencontres & Sorties",
    description: "Discussions et moments agréables, disponible à Kintélé et environs.",
    category: "categorie-a" as const,
    option_type: "option_3" as const,
    mobility: "sur_place" as const,
    city: "brazzaville" as const,
    district: "kintélé",
    price_xaf: 25_000,
    price_unit: "service",
    rates: [],
    cover_url: "https://picsum.photos/seed/grace-22/800/600",
    images: [],
    video_url: null,
    video_poster_url: null,
    rating: 4.2,
    reviews_count: 5,
    is_vip: false,
    is_verified: false,
    is_available_now: true,
    whatsapp_phone: "+242066789012",
    amenities: [],
    languages: ["fr"],
    availability: [],
    created_at: new Date().toISOString(),
    user_id: MOCK_USERS[0].id,
  },
  {
    id: uuidv4(),
    slug: "chantal-24",
    title: "Chantal, 24 ans",
    highlight: "Massage thérapeutique & détente",
    description: "Massage thérapeutique délassant pour soulager le stress et la fatigue.",
    category: "categorie-b" as const,
    option_type: "option_1" as const,
    mobility: "les_deux" as const,
    city: "brazzaville" as const,
    district: "maya-maya",
    price_xaf: 25_000,
    price_unit: "service",
    rates: [],
    cover_url: "https://picsum.photos/seed/chantal-24/800/600",
    images: [],
    video_url: null,
    video_poster_url: null,
    rating: 4.0,
    reviews_count: 3,
    is_vip: false,
    is_verified: false,
    is_available_now: false,
    whatsapp_phone: "+242068901234",
    amenities: [],
    languages: ["fr"],
    availability: [],
    created_at: new Date().toISOString(),
    user_id: MOCK_USERS[1].id,
  },
  {
    id: uuidv4(),
    slug: "massage-zen-2",
    title: "Massage Zen – 90 min",
    highlight: "Massage prolongé à domicile",
    description: "Massage de 90 minutes, + huiles essentielles, à domicile.",
    category: "categorie-b" as const,
    option_type: "option_2" as const,
    mobility: "a_domicile" as const,
    city: "pointe-noire" as const,
    district: null,
    price_xaf: 25_000,
    price_unit: "service",
    rates: [],
    cover_url: "https://picsum.photos/seed/massage-zen-2/800/600",
    images: [],
    video_url: null,
    video_poster_url: null,
    rating: 4.7,
    reviews_count: 10,
    is_vip: false,
    is_verified: true,
    is_available_now: true,
    amenities: ["Huiles essentielles", "Musique relaxante"],
    languages: ["fr"],
    availability: [],
    created_at: new Date().toISOString(),
    user_id: MOCK_USERS[0].id,
  },
];

// Export du type de tableau utilisé dans les listes d'accueil
export const MOCK_LISTING_CARDS: ListingCardData[] = MOCK_LISTINGS.map((l) => ({
  id: l.id,
  slug: l.slug,
  title: l.title,
  highlight: l.highlight,
  city: l.city,
  district: l.district,
  category: l.category,
  price_xaf: l.price_xaf,
  price_unit: l.price_unit,
  cover_url: l.cover_url,
  rating: l.rating,
  is_vip: l.is_vip,
  is_verified: l.is_verified,
  is_available_now: l.is_available_now,
  video_url: l.video_url,
  whatsapp_phone: l.whatsapp_phone,
}));
